version: "3.9"
services:
  bot:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - IMPULSOETL_AMBIENTE=${IMPULSOETL_AMBIENTE}
      - IMPULSOETL_BD_HOST=${IMPULSOETL_BD_HOST}
      - IMPULSOETL_BD_PORTA=${IMPULSOETL_BD_PORTA}
      - IMPULSOETL_BD_NOME=${IMPULSOETL_BD_NOME}
      - IMPULSOETL_BD_USUARIO=${IMPULSOETL_BD_USUARIO}
      - IMPULSOETL_BD_SENHA=${IMPULSOETL_BD_SENHA}
      - TOKEN_SLACK_APP_TRANSMISSOR=${TOKEN_SLACK_APP_TRANSMISSOR}
      - CANAL_SLACK_APP=${CANAL_SLACK_APP}
    volumes:
      - .:/app

