name: Cria imagem Docker - Slackbot Transmissor

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_SENHA: ${{secrets.DOCKER_SENHA}}
      run: docker login -u $DOCKER_USER -p $DOCKER_SENHA
